" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Vim5 and later versions support syntax highlighting.
if has("syntax")
  syntax on
endif

" Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Keep a backup file
if has("vms")
  set nobackup          " do not keep a backup file, use versions
  instead
else
  set backup            " keep a backup file (finishing with ~)
endif

" Vim load indentation rules and plugins according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" Show (partial) command in status line.
" The command will be at the right side, bottom line (near line,column).
set showcmd

" Fast jump to the matching bracket.
set showmatch

" Do smart case matching
" Ignore case when the pattern contains lowercase letters only.
set smartcase

" While typing a search command, show where the pattern,
" as it was typed so far, matches.
set incsearch

" Automatically save before commands like :next and :make etc
set autowrite

" Hide buffers instead of closing them when abandoned.
set hidden

" Show line number.
set number

" Auto indent
set autoindent

" size of the indent
set shiftwidth=2

"  Show the line and column number of the cursor position (bottom - right)
set ruler

" Show history of 25 last commands pressing up or down, when in command mode.
set history=25

" Number of spaces that a <Tab> in the file counts for.
set tabstop=2

" Make tab insert indents instead of tabs at the beginning of a line
set smarttab

" To insert space characters instead of tab.
set expandtab

" Remove whitespaces at end of line
autocmd BufWritePre *.{java,py,c,cpp,C,cc,h,hpp,hh,H,rb,sh} :%s/\s\+$//e

" Highlight whitespace at end of the line.
highlight ExtraWhitespace ctermbg=green guibg=green

" Define what is considered extra whitespace.
match ExtraWhitespace /\s\+$/
